import { Prisma } from '.prisma/client';

export const people: Prisma.PersonCreateInput[] = [
  {
    name: 'Luke Skywalker',
    height: 172,
    mass: 77,
    birthYear: '19BBY',
    eyeColor: 'blue',
    gender: 'male',
    hairColor: 'blond',
    skinColor: 'fair',
  },
  {
    name: 'C-3PO',
    height: 167,
    mass: 75,
    birthYear: '112BBY',
    eyeColor: 'yellow',
    skinColor: 'gold',
  },
  {
    name: 'R2-D2',
    height: 96,
    mass: 32,
    birthYear: '33BBY',
    eyeColor: 'red',
    skinColor: 'white, blue',
  },
  {
    name: 'Darth Vader',
    height: 202,
    mass: 136,
    birthYear: '41.9BBY',
    eyeColor: 'yellow',
    gender: 'male',
    hairColor: 'none',
    skinColor: 'white',
  },
  {
    name: 'Leia Organa',
    height: 150,
    mass: 49,
    birthYear: '19BBY',
    eyeColor: 'brown',
    gender: 'female',
    hairColor: 'brown',
    skinColor: 'light',
  },
  {
    name: 'Owen Lars',
    height: 178,
    mass: 120,
    birthYear: '52BBY',
    eyeColor: 'blue',
    gender: 'male',
    hairColor: 'brown, grey',
    skinColor: 'light',
  },
  {
    name: 'Beru Whitesun lars',
    height: 165,
    mass: 75,
    birthYear: '47BBY',
    eyeColor: 'blue',
    gender: 'female',
    hairColor: 'brown',
    skinColor: 'light',
  },
  {
    name: 'R5-D4',
    height: 97,
    mass: 32,
    birthYear: 'unknown',
    eyeColor: 'red',
    skinColor: 'white, red',
  },
  {
    name: 'Biggs Darklighter',
    height: 183,
    mass: 84,
    birthYear: '24BBY',
    eyeColor: 'brown',
    gender: 'male',
    hairColor: 'black',
    skinColor: 'light',
  },
  {
    name: 'Obi-Wan Kenobi',
    height: 182,
    mass: 77,
    birthYear: '57BBY',
    eyeColor: 'blue-gray',
    gender: 'male',
    hairColor: 'auburn, white',
    skinColor: 'fair',
  },
];
