/**
 * Generated by orval v6.6.4 🍺
 * Do not edit manually.
 * Swagger SW API
 * This is partial implementation of Star Wars API
 * OpenAPI spec version: 1.0.0
 */

export type GetPeopleParams = { take?: number; skip?: number };
