/**
 * Generated by orval v6.6.4 🍺
 * Do not edit manually.
 * Swagger SW API
 * This is partial implementation of Star Wars API
 * OpenAPI spec version: 1.0.0
 */

export type PatchPersonBody = {
  name?: string;
  height?: number;
  mass?: number;
  hairColor?: string;
  skinColor?: string;
  eyeColor?: string;
  birthYear?: string;
  gender?: string;
};
